
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Workspace
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed class DataWorkspace : global::Microsoft.LightSwitch.Framework.Base.DataWorkspace<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of a DataWorkspace.  Changes can be made to data sources in the new instance independent of changes made to data sources in the default DataWorkspace.
        /// </summary>
        public DataWorkspace() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the ContosoMotorsCarInventory datasource.  This provides members to query and update data in the data source.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.ContosoMotorsCarInventoryService ContosoMotorsCarInventory
        {
            get
            {
                return global::LightSwitchApplication.DataWorkspace.DetailsClass.GetValue(this, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.ContosoMotorsCarInventory);
            }
        }
        
        /// <summary>
        /// Gets the ContosoMotorsPictureLibrary datasource.  This provides members to query and update data in the data source.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.ContosoMotorsPictureLibraryService ContosoMotorsPictureLibrary
        {
            get
            {
                return global::LightSwitchApplication.DataWorkspace.DetailsClass.GetValue(this, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.ContosoMotorsPictureLibrary);
            }
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspaceDetails<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.ContosoMotorsCarInventory;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspacePropertySet<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ContosoMotorsCarInventoryService> ContosoMotorsCarInventory
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.ContosoMotorsCarInventory) as global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ContosoMotorsCarInventoryService>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ContosoMotorsPictureLibraryService> ContosoMotorsPictureLibrary
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.ContosoMotorsPictureLibrary) as global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ContosoMotorsPictureLibraryService>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ContosoMotorsCarInventoryService>.Entry
                    ContosoMotorsCarInventory = new global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ContosoMotorsCarInventoryService>.Entry(
                        "ContosoMotorsCarInventory",
                        global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties._ContosoMotorsCarInventory_Stub);
                private static void _ContosoMotorsCarInventory_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DataWorkspace.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ContosoMotorsCarInventoryService>.Data> c, global::LightSwitchApplication.DataWorkspace.DetailsClass d, object sf)
                {
                    c(d, ref d._ContosoMotorsCarInventory, sf);
                }
                 
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ContosoMotorsPictureLibraryService>.Entry
                    ContosoMotorsPictureLibrary = new global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ContosoMotorsPictureLibraryService>.Entry(
                        "ContosoMotorsPictureLibrary",
                        global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties._ContosoMotorsPictureLibrary_Stub);
                private static void _ContosoMotorsPictureLibrary_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DataWorkspace.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ContosoMotorsPictureLibraryService>.Data> c, global::LightSwitchApplication.DataWorkspace.DetailsClass d, object sf)
                {
                    c(d, ref d._ContosoMotorsPictureLibrary, sf);
                }
                 
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ContosoMotorsCarInventoryService>.Data _ContosoMotorsCarInventory;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.ContosoMotorsPictureLibraryService>.Data _ContosoMotorsPictureLibrary;
            
        }
    
        #endregion
    }
    
    #endregion
    
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the ContosoMotorsCarInventory datasource.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ContosoMotorsCarInventory : global::Microsoft.LightSwitch.Framework.Base.DataService<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// This constructor is used for the internal LightSwitch framework. Use DataWorkspace instead.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public ContosoMotorsCarInventory() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the InventoryItems entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.InventoryItem> InventoryItems
        {
            get
            {
                return global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass.GetValue(this, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass.PropertySetProperties.InventoryItems);
            }
        }
        
        #endregion
    
        #region Queries
    
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="ID">
        /// The value of the 'ID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.InventoryItem InventoryItems_Single(global::System.Nullable<int> ID)
        {
            return this.Details.Methods.InventoryItems_Single.CreateInvocation(ID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="ID">
        /// The value of the 'ID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.InventoryItem InventoryItems_SingleOrDefault(global::System.Nullable<int> ID)
        {
            return this.Details.Methods.InventoryItems_SingleOrDefault.CreateInvocation(ID).Execute();
        }
        
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        /// <param name="SearchParam">
        /// No Modeled Description Available
        /// </param>
        /// <param name="SortColumn">
        /// No Modeled Description Available
        /// </param>
        /// <param name="SortOrder">
        /// No Modeled Description Available
        /// </param>
        /// <param name="PageParam">
        /// No Modeled Description Available
        /// </param>
        public global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.InventoryItem> ContosoMotorsQuery(string SearchParam, string SortColumn, global::System.Nullable<int> SortOrder, global::System.Nullable<int> PageParam)
        {
            return this.Details.Methods.ContosoMotorsQuery.CreateInvocation(SearchParam, SortColumn, SortOrder, PageParam).Execute();
        }
        
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        /// <param name="searchParam">
        /// No Modeled Description Available
        /// </param>
        /// <param name="sortColumn">
        /// No Modeled Description Available
        /// </param>
        /// <param name="sortOrder">
        /// No Modeled Description Available
        /// </param>
        /// <param name="pageParam">
        /// No Modeled Description Available
        /// </param>
        public global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.InventoryItem> GetFilteredCarInventory(string searchParam, string sortColumn, global::System.Nullable<int> sortOrder, global::System.Nullable<int> pageParam)
        {
            return this.Details.Methods.GetFilteredCarInventory.CreateInvocation(searchParam, sortColumn, sortOrder, pageParam).Execute();
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceDetails<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass.PropertySet, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass.MethodSet>
        {
    
            static DetailsClass()
            {
                var initializeMethodEntry = global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass.MethodSetProperties.InventoryItems_Single;
                var initializePropertyEntry = global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass.PropertySetProperties.InventoryItems;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceMethodSet<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass>
            {
    
                public MethodSet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem> InventoryItems_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass.MethodSetProperties.InventoryItems_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem> InventoryItems_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass.MethodSetProperties.InventoryItems_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem> ContosoMotorsQuery
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass.MethodSetProperties.ContosoMotorsQuery) as global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem> GetFilteredCarInventory
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass.MethodSetProperties.GetFilteredCarInventory) as global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServicePropertySet<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem> InventoryItems
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass.PropertySetProperties.InventoryItems) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class MethodSetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem>.Entry
                    InventoryItems_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem>.Entry(
                        "InventoryItems_Single",
                        global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass.MethodSetProperties._InventoryItems_Single_Stub);
                private static void _InventoryItems_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem>.Data> c, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass d, object sf)
                {
                    c(d, ref d._InventoryItems_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem>.Entry
                    InventoryItems_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem>.Entry(
                        "InventoryItems_SingleOrDefault",
                        global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass.MethodSetProperties._InventoryItems_SingleOrDefault_Stub);
                private static void _InventoryItems_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem>.Data> c, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass d, object sf)
                {
                    c(d, ref d._InventoryItems_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem>.Entry
                    ContosoMotorsQuery = new global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem>.Entry(
                        "ContosoMotorsQuery",
                        global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass.MethodSetProperties._ContosoMotorsQuery_Stub);
                private static void _ContosoMotorsQuery_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem>.Data> c, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass d, object sf)
                {
                    c(d, ref d._ContosoMotorsQuery, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem>.Entry
                    GetFilteredCarInventory = new global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem>.Entry(
                        "GetFilteredCarInventory",
                        global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass.MethodSetProperties._GetFilteredCarInventory_Stub);
                private static void _GetFilteredCarInventory_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem>.Data> c, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass d, object sf)
                {
                    c(d, ref d._GetFilteredCarInventory, sf);
                }
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem>.Entry
                    InventoryItems = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem>.Entry(
                        "InventoryItems",
                        global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass.PropertySetProperties._InventoryItems_Stub);
                private static void _InventoryItems_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem>.Data> c, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass d, object sf)
                {
                    c(d, ref d._InventoryItems, sf);
                }
     
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem>.Data _InventoryItems;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem>.Data _InventoryItems_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem>.Data _InventoryItems_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem>.Data _ContosoMotorsQuery;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.ContosoMotorsCarInventory, global::LightSwitchApplication.ContosoMotorsCarInventory.DetailsClass, global::LightSwitchApplication.InventoryItem>.Data _GetFilteredCarInventory;
            
        }
    
        #endregion
    }
    
    /// <summary>
    /// Provides members to query and update data in the ContosoMotorsPictureLibrary datasource.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class ContosoMotorsPictureLibrary : global::Microsoft.LightSwitch.Framework.Base.DataService<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// This constructor is used for the internal LightSwitch framework. Use DataWorkspace instead.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public ContosoMotorsPictureLibrary() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the ContosoMotorsPictures entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ContosoMotorsPicture> ContosoMotorsPictures
        {
            get
            {
                return global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass.GetValue(this, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass.PropertySetProperties.ContosoMotorsPictures);
            }
        }
        
        /// <summary>
        /// Gets the UserInformationLists entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.UserInformationList> UserInformationLists
        {
            get
            {
                return global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass.GetValue(this, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass.PropertySetProperties.UserInformationLists);
            }
        }
        
        #endregion
    
        #region Queries
    
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.ContosoMotorsPicture ContosoMotorsPictures_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.ContosoMotorsPictures_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.ContosoMotorsPicture ContosoMotorsPictures_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.ContosoMotorsPictures_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.UserInformationList UserInformationLists_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.UserInformationLists_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.UserInformationList UserInformationLists_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.UserInformationLists_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceDetails<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass.PropertySet, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass.MethodSet>
        {
    
            static DetailsClass()
            {
                var initializeMethodEntry = global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass.MethodSetProperties.ContosoMotorsPictures_Single;
                var initializePropertyEntry = global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass.PropertySetProperties.ContosoMotorsPictures;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceMethodSet<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass>
            {
    
                public MethodSet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.ContosoMotorsPicture> ContosoMotorsPictures_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass.MethodSetProperties.ContosoMotorsPictures_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.ContosoMotorsPicture>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.ContosoMotorsPicture> ContosoMotorsPictures_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass.MethodSetProperties.ContosoMotorsPictures_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.ContosoMotorsPicture>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.UserInformationList> UserInformationLists_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass.MethodSetProperties.UserInformationLists_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.UserInformationList>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.UserInformationList> UserInformationLists_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass.MethodSetProperties.UserInformationLists_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.UserInformationList>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServicePropertySet<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.ContosoMotorsPicture> ContosoMotorsPictures
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass.PropertySetProperties.ContosoMotorsPictures) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.ContosoMotorsPicture>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.UserInformationList> UserInformationLists
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass.PropertySetProperties.UserInformationLists) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.UserInformationList>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class MethodSetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.ContosoMotorsPicture>.Entry
                    ContosoMotorsPictures_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.ContosoMotorsPicture>.Entry(
                        "ContosoMotorsPictures_Single",
                        global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass.MethodSetProperties._ContosoMotorsPictures_Single_Stub);
                private static void _ContosoMotorsPictures_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.ContosoMotorsPicture>.Data> c, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass d, object sf)
                {
                    c(d, ref d._ContosoMotorsPictures_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.ContosoMotorsPicture>.Entry
                    ContosoMotorsPictures_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.ContosoMotorsPicture>.Entry(
                        "ContosoMotorsPictures_SingleOrDefault",
                        global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass.MethodSetProperties._ContosoMotorsPictures_SingleOrDefault_Stub);
                private static void _ContosoMotorsPictures_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.ContosoMotorsPicture>.Data> c, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass d, object sf)
                {
                    c(d, ref d._ContosoMotorsPictures_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.UserInformationList>.Entry
                    UserInformationLists_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.UserInformationList>.Entry(
                        "UserInformationLists_Single",
                        global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass.MethodSetProperties._UserInformationLists_Single_Stub);
                private static void _UserInformationLists_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.UserInformationList>.Data> c, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass d, object sf)
                {
                    c(d, ref d._UserInformationLists_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.UserInformationList>.Entry
                    UserInformationLists_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.UserInformationList>.Entry(
                        "UserInformationLists_SingleOrDefault",
                        global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass.MethodSetProperties._UserInformationLists_SingleOrDefault_Stub);
                private static void _UserInformationLists_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.UserInformationList>.Data> c, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass d, object sf)
                {
                    c(d, ref d._UserInformationLists_SingleOrDefault, sf);
                }
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.ContosoMotorsPicture>.Entry
                    ContosoMotorsPictures = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.ContosoMotorsPicture>.Entry(
                        "ContosoMotorsPictures",
                        global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass.PropertySetProperties._ContosoMotorsPictures_Stub);
                private static void _ContosoMotorsPictures_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.ContosoMotorsPicture>.Data> c, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass d, object sf)
                {
                    c(d, ref d._ContosoMotorsPictures, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.UserInformationList>.Entry
                    UserInformationLists = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.UserInformationList>.Entry(
                        "UserInformationLists",
                        global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass.PropertySetProperties._UserInformationLists_Stub);
                private static void _UserInformationLists_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.UserInformationList>.Data> c, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass d, object sf)
                {
                    c(d, ref d._UserInformationLists, sf);
                }
     
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.ContosoMotorsPicture>.Data _ContosoMotorsPictures;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.UserInformationList>.Data _UserInformationLists;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.ContosoMotorsPicture>.Data _ContosoMotorsPictures_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.ContosoMotorsPicture>.Data _ContosoMotorsPictures_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.UserInformationList>.Data _UserInformationLists_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.ContosoMotorsPictureLibrary, global::LightSwitchApplication.ContosoMotorsPictureLibrary.DetailsClass, global::LightSwitchApplication.UserInformationList>.Data _UserInformationLists_SingleOrDefault;
            
        }
    
        #endregion
    }
    
    #endregion
    
}
