//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the ContosoMotorsCarInventory datasource.
    /// </summary>
    public sealed partial class ContosoMotorsCarInventoryService
        : global::LightSwitchApplication.ContosoMotorsCarInventory
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ContosoMotorsCarInventoryService() : base()
        {
        }
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Server Interceptions Points
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InventoryItems_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InventoryItems_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InventoryItems_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InventoryItems_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InventoryItems_Inserting(global::LightSwitchApplication.InventoryItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InventoryItems_Inserted(global::LightSwitchApplication.InventoryItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InventoryItems_Updating(global::LightSwitchApplication.InventoryItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InventoryItems_Updated(global::LightSwitchApplication.InventoryItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InventoryItems_Deleting(global::LightSwitchApplication.InventoryItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InventoryItems_Deleted(global::LightSwitchApplication.InventoryItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InventoryItems_Validate(global::LightSwitchApplication.InventoryItem entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executed();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContosoMotorsQuery_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void ContosoMotorsQuery_Executing(string SearchParam, string SortColumn, global::System.Nullable<int> SortOrder, global::System.Nullable<int> PageParam);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContosoMotorsQuery_PreprocessQuery(string SearchParam, string SortColumn, global::System.Nullable<int> SortOrder, global::System.Nullable<int> PageParam, ref global::System.Linq.IQueryable<global::LightSwitchApplication.InventoryItem> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void ContosoMotorsQuery_Executed(string SearchParam, string SortColumn, global::System.Nullable<int> SortOrder, global::System.Nullable<int> PageParam, global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.InventoryItem> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void ContosoMotorsQuery_ExecuteFailed(string SearchParam, string SortColumn, global::System.Nullable<int> SortOrder, global::System.Nullable<int> PageParam, global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void GetFilteredCarInventory_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void GetFilteredCarInventory_Executing(string searchParam, string sortColumn, global::System.Nullable<int> sortOrder, global::System.Nullable<int> pageParam);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void GetFilteredCarInventory_PreprocessQuery(string searchParam, string sortColumn, global::System.Nullable<int> sortOrder, global::System.Nullable<int> pageParam, ref global::System.Linq.IQueryable<global::LightSwitchApplication.InventoryItem> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void GetFilteredCarInventory_Executed(string searchParam, string sortColumn, global::System.Nullable<int> sortOrder, global::System.Nullable<int> pageParam, global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.InventoryItem> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void GetFilteredCarInventory_ExecuteFailed(string searchParam, string sortColumn, global::System.Nullable<int> sortOrder, global::System.Nullable<int> pageParam, global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executing(global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executed(global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_ExecuteFailed(global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor);
    
        #endregion
    
        #region Details Class
    
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        public static new class DetailsClass
        {
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline")]
            static DetailsClass()
            {
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ContosoMotorsCarInventoryService, global::LightSwitchApplication.InventoryItem>
                __InventoryItemsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ContosoMotorsCarInventoryService, global::LightSwitchApplication.InventoryItem>(
                    "InventoryItems",
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__InventoryItems_CanInsert,
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__InventoryItems_CanUpdate,
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__InventoryItems_CanDelete,
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__InventoryItems_CanRead,
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__InventoryItems_Inserting,
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__InventoryItems_Inserted,
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__InventoryItems_Updating,
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__InventoryItems_Updated,
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__InventoryItems_Deleting,
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__InventoryItems_Deleted,
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__InventoryItems_Validate,
                    null);
            private static bool __InventoryItems_CanInsert(global::LightSwitchApplication.ContosoMotorsCarInventoryService d)
            {
                bool result = true;
                d.InventoryItems_CanInsert(ref result);
                return result;
            }
            private static bool __InventoryItems_CanUpdate(global::LightSwitchApplication.ContosoMotorsCarInventoryService d)
            {
                bool result = true;
                d.InventoryItems_CanUpdate(ref result);
                return result;
            }
            private static bool __InventoryItems_CanDelete(global::LightSwitchApplication.ContosoMotorsCarInventoryService d)
            {
                bool result = true;
                d.InventoryItems_CanDelete(ref result);
                return result;
            }
            private static bool __InventoryItems_CanRead(global::LightSwitchApplication.ContosoMotorsCarInventoryService d)
            {
                bool result = true;
                d.InventoryItems_CanRead(ref result);
                return result;
            }
            private static void __InventoryItems_Inserting(global::LightSwitchApplication.ContosoMotorsCarInventoryService d, global::LightSwitchApplication.InventoryItem e)
            {
                d.InventoryItems_Inserting(e);
            }
            private static void __InventoryItems_Inserted(global::LightSwitchApplication.ContosoMotorsCarInventoryService d, global::LightSwitchApplication.InventoryItem e)
            {
                d.InventoryItems_Inserted(e);
            }
            private static void __InventoryItems_Updating(global::LightSwitchApplication.ContosoMotorsCarInventoryService d, global::LightSwitchApplication.InventoryItem e)
            {
                d.InventoryItems_Updating(e);
            }
            private static void __InventoryItems_Updated(global::LightSwitchApplication.ContosoMotorsCarInventoryService d, global::LightSwitchApplication.InventoryItem e)
            {
                d.InventoryItems_Updated(e);
            }
            private static void __InventoryItems_Deleting(global::LightSwitchApplication.ContosoMotorsCarInventoryService d, global::LightSwitchApplication.InventoryItem e)
            {
                d.InventoryItems_Deleting(e);
            }
            private static void __InventoryItems_Deleted(global::LightSwitchApplication.ContosoMotorsCarInventoryService d, global::LightSwitchApplication.InventoryItem e)
            {
                d.InventoryItems_Deleted(e);
            }
            private static void __InventoryItems_Validate(global::LightSwitchApplication.ContosoMotorsCarInventoryService d, global::LightSwitchApplication.InventoryItem e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.InventoryItems_Validate(e, r);
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ContosoMotorsCarInventoryService>
                __SaveChangesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ContosoMotorsCarInventoryService>(
                    "SaveChanges",
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__SaveChanges_CanExecute,
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__SaveChanges_Executing,
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__SaveChanges_Executed,
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__SaveChanges_Failed);
            private static bool __SaveChanges_CanExecute(global::LightSwitchApplication.ContosoMotorsCarInventoryService d, bool r)
            {
                d.SaveChanges_CanExecute(ref r);
                return r;
            }
            private static void __SaveChanges_Executing(global::LightSwitchApplication.ContosoMotorsCarInventoryService d, object[] args)
            {
                d.SaveChanges_Executing();
            }
            private static void __SaveChanges_Executed(global::LightSwitchApplication.ContosoMotorsCarInventoryService d, object[] args)
            {
                d.SaveChanges_Executed();
            }
            private static void __SaveChanges_Failed(global::LightSwitchApplication.ContosoMotorsCarInventoryService d, object[] args, global::System.Exception ex)
            {
                d.SaveChanges_ExecuteFailed(ex);
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ContosoMotorsCarInventoryService, global::LightSwitchApplication.InventoryItem>
                __ContosoMotorsQueryEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ContosoMotorsCarInventoryService, global::LightSwitchApplication.InventoryItem>(
                    "ContosoMotorsQuery",
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__ContosoMotorsQuery_CanExecute,
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__ContosoMotorsQuery_Executing,
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__ContosoMotorsQuery_Executed,
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__ContosoMotorsQuery_Failed,
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__ContosoMotorsQuery_PreprocessQuery);
            private static bool __ContosoMotorsQuery_CanExecute(global::LightSwitchApplication.ContosoMotorsCarInventoryService d, bool r)
            {
                d.ContosoMotorsQuery_CanExecute(ref r);
                return r;
            }
            private static void __ContosoMotorsQuery_Executing(global::LightSwitchApplication.ContosoMotorsCarInventoryService d, object[] args)
            {
                d.ContosoMotorsQuery_Executing((string)args[0], (string)args[1], (global::System.Nullable<int>)args[2], (global::System.Nullable<int>)args[3]);
            }
            private static void __ContosoMotorsQuery_Executed(global::LightSwitchApplication.ContosoMotorsCarInventoryService d, object[] args)
            {
                d.ContosoMotorsQuery_Executed((string)args[0], (string)args[1], (global::System.Nullable<int>)args[2], (global::System.Nullable<int>)args[3], (global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.InventoryItem>)args[4]);
            }
            private static void __ContosoMotorsQuery_Failed(global::LightSwitchApplication.ContosoMotorsCarInventoryService d, object[] args, global::System.Exception ex)
            {
                d.ContosoMotorsQuery_ExecuteFailed((string)args[0], (string)args[1], (global::System.Nullable<int>)args[2], (global::System.Nullable<int>)args[3], ex);
            }
            private static global::System.Linq.IQueryable __ContosoMotorsQuery_PreprocessQuery(global::LightSwitchApplication.ContosoMotorsCarInventoryService d, object[] args)
            {
                global::System.Linq.IQueryable<global::LightSwitchApplication.InventoryItem> query = (global::System.Linq.IQueryable<global::LightSwitchApplication.InventoryItem>)args[4];
                d.ContosoMotorsQuery_PreprocessQuery((string)args[0], (string)args[1], (global::System.Nullable<int>)args[2], (global::System.Nullable<int>)args[3], ref query);
                return query;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ContosoMotorsCarInventoryService, global::LightSwitchApplication.InventoryItem>
                __GetFilteredCarInventoryEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ContosoMotorsCarInventoryService, global::LightSwitchApplication.InventoryItem>(
                    "GetFilteredCarInventory",
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__GetFilteredCarInventory_CanExecute,
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__GetFilteredCarInventory_Executing,
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__GetFilteredCarInventory_Executed,
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__GetFilteredCarInventory_Failed,
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__GetFilteredCarInventory_PreprocessQuery);
            private static bool __GetFilteredCarInventory_CanExecute(global::LightSwitchApplication.ContosoMotorsCarInventoryService d, bool r)
            {
                d.GetFilteredCarInventory_CanExecute(ref r);
                return r;
            }
            private static void __GetFilteredCarInventory_Executing(global::LightSwitchApplication.ContosoMotorsCarInventoryService d, object[] args)
            {
                d.GetFilteredCarInventory_Executing((string)args[0], (string)args[1], (global::System.Nullable<int>)args[2], (global::System.Nullable<int>)args[3]);
            }
            private static void __GetFilteredCarInventory_Executed(global::LightSwitchApplication.ContosoMotorsCarInventoryService d, object[] args)
            {
                d.GetFilteredCarInventory_Executed((string)args[0], (string)args[1], (global::System.Nullable<int>)args[2], (global::System.Nullable<int>)args[3], (global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.InventoryItem>)args[4]);
            }
            private static void __GetFilteredCarInventory_Failed(global::LightSwitchApplication.ContosoMotorsCarInventoryService d, object[] args, global::System.Exception ex)
            {
                d.GetFilteredCarInventory_ExecuteFailed((string)args[0], (string)args[1], (global::System.Nullable<int>)args[2], (global::System.Nullable<int>)args[3], ex);
            }
            private static global::System.Linq.IQueryable __GetFilteredCarInventory_PreprocessQuery(global::LightSwitchApplication.ContosoMotorsCarInventoryService d, object[] args)
            {
                global::System.Linq.IQueryable<global::LightSwitchApplication.InventoryItem> query = (global::System.Linq.IQueryable<global::LightSwitchApplication.InventoryItem>)args[4];
                d.GetFilteredCarInventory_PreprocessQuery((string)args[0], (string)args[1], (global::System.Nullable<int>)args[2], (global::System.Nullable<int>)args[3], ref query);
                return query;
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ContosoMotorsCarInventoryService>
                ___QueryEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ContosoMotorsCarInventoryService>(
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__Query_Executing,
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__Query_Executed,
                    global::LightSwitchApplication.ContosoMotorsCarInventoryService.DetailsClass.__Query_Failed);
            private static void __Query_Executing(global::LightSwitchApplication.ContosoMotorsCarInventoryService d, global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor)
            {
                d.Query_Executing(queryDescriptor);
            }
            private static void __Query_Executed(global::LightSwitchApplication.ContosoMotorsCarInventoryService d, global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor)
            {
                d.Query_Executed(queryDescriptor);
            }
            private static void __Query_Failed(global::LightSwitchApplication.ContosoMotorsCarInventoryService d, global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor)
            {
                d.Query_ExecuteFailed(queryDescriptor);
            }
        }
    
        #endregion
    }
    
    /// <summary>
    /// Provides members to query and update data in the ContosoMotorsPictureLibrary datasource.
    /// </summary>
    public sealed partial class ContosoMotorsPictureLibraryService
        : global::LightSwitchApplication.ContosoMotorsPictureLibrary
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ContosoMotorsPictureLibraryService() : base()
        {
        }
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Server Interceptions Points
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContosoMotorsPictures_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContosoMotorsPictures_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContosoMotorsPictures_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContosoMotorsPictures_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContosoMotorsPictures_Inserting(global::LightSwitchApplication.ContosoMotorsPicture entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContosoMotorsPictures_Inserted(global::LightSwitchApplication.ContosoMotorsPicture entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContosoMotorsPictures_Updating(global::LightSwitchApplication.ContosoMotorsPicture entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContosoMotorsPictures_Updated(global::LightSwitchApplication.ContosoMotorsPicture entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContosoMotorsPictures_Deleting(global::LightSwitchApplication.ContosoMotorsPicture entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContosoMotorsPictures_Deleted(global::LightSwitchApplication.ContosoMotorsPicture entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContosoMotorsPictures_Validate(global::LightSwitchApplication.ContosoMotorsPicture entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserInformationLists_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserInformationLists_Validate(global::LightSwitchApplication.UserInformationList entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executed();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executing(global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executed(global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_ExecuteFailed(global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContosoMotorsPictureLibrary_SendingRequest(global::Microsoft.LightSwitch.ODataSendingState state);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContosoMotorsPictureLibrary_ReceivedResponse(global::Microsoft.LightSwitch.ODataReceivedState state);
    
        #endregion
    
        #region Details Class
    
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        public static new class DetailsClass
        {
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline")]
            static DetailsClass()
            {
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ContosoMotorsPictureLibraryService, global::LightSwitchApplication.ContosoMotorsPicture>
                __ContosoMotorsPicturesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ContosoMotorsPictureLibraryService, global::LightSwitchApplication.ContosoMotorsPicture>(
                    "ContosoMotorsPictures",
                    global::LightSwitchApplication.ContosoMotorsPictureLibraryService.DetailsClass.__ContosoMotorsPictures_CanInsert,
                    global::LightSwitchApplication.ContosoMotorsPictureLibraryService.DetailsClass.__ContosoMotorsPictures_CanUpdate,
                    global::LightSwitchApplication.ContosoMotorsPictureLibraryService.DetailsClass.__ContosoMotorsPictures_CanDelete,
                    global::LightSwitchApplication.ContosoMotorsPictureLibraryService.DetailsClass.__ContosoMotorsPictures_CanRead,
                    global::LightSwitchApplication.ContosoMotorsPictureLibraryService.DetailsClass.__ContosoMotorsPictures_Inserting,
                    global::LightSwitchApplication.ContosoMotorsPictureLibraryService.DetailsClass.__ContosoMotorsPictures_Inserted,
                    global::LightSwitchApplication.ContosoMotorsPictureLibraryService.DetailsClass.__ContosoMotorsPictures_Updating,
                    global::LightSwitchApplication.ContosoMotorsPictureLibraryService.DetailsClass.__ContosoMotorsPictures_Updated,
                    global::LightSwitchApplication.ContosoMotorsPictureLibraryService.DetailsClass.__ContosoMotorsPictures_Deleting,
                    global::LightSwitchApplication.ContosoMotorsPictureLibraryService.DetailsClass.__ContosoMotorsPictures_Deleted,
                    global::LightSwitchApplication.ContosoMotorsPictureLibraryService.DetailsClass.__ContosoMotorsPictures_Validate,
                    null);
            private static bool __ContosoMotorsPictures_CanInsert(global::LightSwitchApplication.ContosoMotorsPictureLibraryService d)
            {
                bool result = true;
                d.ContosoMotorsPictures_CanInsert(ref result);
                return result;
            }
            private static bool __ContosoMotorsPictures_CanUpdate(global::LightSwitchApplication.ContosoMotorsPictureLibraryService d)
            {
                bool result = true;
                d.ContosoMotorsPictures_CanUpdate(ref result);
                return result;
            }
            private static bool __ContosoMotorsPictures_CanDelete(global::LightSwitchApplication.ContosoMotorsPictureLibraryService d)
            {
                bool result = true;
                d.ContosoMotorsPictures_CanDelete(ref result);
                return result;
            }
            private static bool __ContosoMotorsPictures_CanRead(global::LightSwitchApplication.ContosoMotorsPictureLibraryService d)
            {
                bool result = true;
                d.ContosoMotorsPictures_CanRead(ref result);
                return result;
            }
            private static void __ContosoMotorsPictures_Inserting(global::LightSwitchApplication.ContosoMotorsPictureLibraryService d, global::LightSwitchApplication.ContosoMotorsPicture e)
            {
                d.ContosoMotorsPictures_Inserting(e);
            }
            private static void __ContosoMotorsPictures_Inserted(global::LightSwitchApplication.ContosoMotorsPictureLibraryService d, global::LightSwitchApplication.ContosoMotorsPicture e)
            {
                d.ContosoMotorsPictures_Inserted(e);
            }
            private static void __ContosoMotorsPictures_Updating(global::LightSwitchApplication.ContosoMotorsPictureLibraryService d, global::LightSwitchApplication.ContosoMotorsPicture e)
            {
                d.ContosoMotorsPictures_Updating(e);
            }
            private static void __ContosoMotorsPictures_Updated(global::LightSwitchApplication.ContosoMotorsPictureLibraryService d, global::LightSwitchApplication.ContosoMotorsPicture e)
            {
                d.ContosoMotorsPictures_Updated(e);
            }
            private static void __ContosoMotorsPictures_Deleting(global::LightSwitchApplication.ContosoMotorsPictureLibraryService d, global::LightSwitchApplication.ContosoMotorsPicture e)
            {
                d.ContosoMotorsPictures_Deleting(e);
            }
            private static void __ContosoMotorsPictures_Deleted(global::LightSwitchApplication.ContosoMotorsPictureLibraryService d, global::LightSwitchApplication.ContosoMotorsPicture e)
            {
                d.ContosoMotorsPictures_Deleted(e);
            }
            private static void __ContosoMotorsPictures_Validate(global::LightSwitchApplication.ContosoMotorsPictureLibraryService d, global::LightSwitchApplication.ContosoMotorsPicture e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.ContosoMotorsPictures_Validate(e, r);
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ContosoMotorsPictureLibraryService, global::LightSwitchApplication.UserInformationList>
                __UserInformationListsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ContosoMotorsPictureLibraryService, global::LightSwitchApplication.UserInformationList>(
                    "UserInformationLists",
                    null,
                    null,
                    null,
                    global::LightSwitchApplication.ContosoMotorsPictureLibraryService.DetailsClass.__UserInformationLists_CanRead,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    global::LightSwitchApplication.ContosoMotorsPictureLibraryService.DetailsClass.__UserInformationLists_Validate,
                    null);
            private static bool __UserInformationLists_CanRead(global::LightSwitchApplication.ContosoMotorsPictureLibraryService d)
            {
                bool result = true;
                d.UserInformationLists_CanRead(ref result);
                return result;
            }
            private static void __UserInformationLists_Validate(global::LightSwitchApplication.ContosoMotorsPictureLibraryService d, global::LightSwitchApplication.UserInformationList e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.UserInformationLists_Validate(e, r);
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ContosoMotorsPictureLibraryService>
                __SaveChangesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ContosoMotorsPictureLibraryService>(
                    "SaveChanges",
                    global::LightSwitchApplication.ContosoMotorsPictureLibraryService.DetailsClass.__SaveChanges_CanExecute,
                    global::LightSwitchApplication.ContosoMotorsPictureLibraryService.DetailsClass.__SaveChanges_Executing,
                    global::LightSwitchApplication.ContosoMotorsPictureLibraryService.DetailsClass.__SaveChanges_Executed,
                    global::LightSwitchApplication.ContosoMotorsPictureLibraryService.DetailsClass.__SaveChanges_Failed);
            private static bool __SaveChanges_CanExecute(global::LightSwitchApplication.ContosoMotorsPictureLibraryService d, bool r)
            {
                d.SaveChanges_CanExecute(ref r);
                return r;
            }
            private static void __SaveChanges_Executing(global::LightSwitchApplication.ContosoMotorsPictureLibraryService d, object[] args)
            {
                d.SaveChanges_Executing();
            }
            private static void __SaveChanges_Executed(global::LightSwitchApplication.ContosoMotorsPictureLibraryService d, object[] args)
            {
                d.SaveChanges_Executed();
            }
            private static void __SaveChanges_Failed(global::LightSwitchApplication.ContosoMotorsPictureLibraryService d, object[] args, global::System.Exception ex)
            {
                d.SaveChanges_ExecuteFailed(ex);
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ContosoMotorsPictureLibraryService>
                ___QueryEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ContosoMotorsPictureLibraryService>(
                    global::LightSwitchApplication.ContosoMotorsPictureLibraryService.DetailsClass.__Query_Executing,
                    global::LightSwitchApplication.ContosoMotorsPictureLibraryService.DetailsClass.__Query_Executed,
                    global::LightSwitchApplication.ContosoMotorsPictureLibraryService.DetailsClass.__Query_Failed);
            private static void __Query_Executing(global::LightSwitchApplication.ContosoMotorsPictureLibraryService d, global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor)
            {
                d.Query_Executing(queryDescriptor);
            }
            private static void __Query_Executed(global::LightSwitchApplication.ContosoMotorsPictureLibraryService d, global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor)
            {
                d.Query_Executed(queryDescriptor);
            }
            private static void __Query_Failed(global::LightSwitchApplication.ContosoMotorsPictureLibraryService d, global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor)
            {
                d.Query_ExecuteFailed(queryDescriptor);
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.ODataServiceAuthEntry<global::LightSwitchApplication.ContosoMotorsPictureLibraryService>
                ___ODataServiceAuthEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.ODataServiceAuthEntry<global::LightSwitchApplication.ContosoMotorsPictureLibraryService>(
                    global::LightSwitchApplication.ContosoMotorsPictureLibraryService.DetailsClass.__ContosoMotorsPictureLibrary_SendingRequest,
                    global::LightSwitchApplication.ContosoMotorsPictureLibraryService.DetailsClass.__ContosoMotorsPictureLibrary_ReceivedResponse);
            private static void __ContosoMotorsPictureLibrary_SendingRequest(global::LightSwitchApplication.ContosoMotorsPictureLibraryService d, global::Microsoft.LightSwitch.ODataSendingState state)
            {
                d.ContosoMotorsPictureLibrary_SendingRequest(state);
            }
            private static void __ContosoMotorsPictureLibrary_ReceivedResponse(global::LightSwitchApplication.ContosoMotorsPictureLibraryService d, global::Microsoft.LightSwitch.ODataReceivedState state)
            {
                d.ContosoMotorsPictureLibrary_ReceivedResponse(state);
            }
        }
    
        #endregion
    }
    
    #endregion
}
